name: Build and Release for Windows and Linux

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller replace_vars.py --onefile

      - name: Rename output for platform
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/replace_vars.exe dist/replace_vars-windows.exe
          else
            mv dist/replace_vars dist/replace_vars-linux
          fi
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/replace_vars-windows.exe
            dist/replace_vars-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}