name: Build for Windows, Linux (CentOS 7), and macOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable (Win/macOS only)
        if: matrix.os != 'ubuntu-latest'
        run: pyinstaller replace_vars.py --onefile

      - name: Upload artifact (Win/macOS)
        if: matrix.os != 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/replace_vars*

  build-linux-centos7:
    name: Build on CentOS 7 (for Linux compatibility)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build in CentOS 7 container
        run: |
          docker run --rm -v "$PWD":/app -w /app centos:7 bash -c "
            curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo &&
            yum clean all && yum makecache fast &&
            yum install -y gcc gcc-c++ make wget python3 python3-devel &&
            pip3 install --upgrade pip &&
            pip3 install wheel &&
            pip3 install pyinstaller &&
            pyinstaller replace_vars.py --onefile &&
            mv dist/replace_vars /app/replace_vars-linux-centos7
          "

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-centos7-build
          path: replace_vars-linux-centos7