name: Build for Windows, Linux (CentOS 7), and macOS

on:
  push:
    tags:
      - 'v*-win'

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable (Win/macOS only)
        run: pyinstaller replace_vars.py --onefile

      - name: Upload artifact (Win/macOS)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/replace_vars*